### PR TITLE
Document Styling Fixes

### PR DESCRIPTION
**Pull request by g-luo**

### CODE REVIEW

**Comment by g-luo** [comment]
Screenshot 2020-07-28 at 11 36 16 AM - Display 2

**Review by tin0d0 — APPROVED** [review]
lgtm!

**Review by max-friedman — APPROVED** [review]
lgtm

**Review by jileiwang-google — APPROVED** [review]
LGTM

**Review by HidyHan — APPROVED** [review]

**Review by frankpzn — APPROVED** [review]

**Pull request merged**
