### PR TITLE
Add 100+ languages

### PR DESCRIPTION
**Pull request by tin0d0**
- Add the 100+ languages 
- All files are imported from code mirror, none are original

### CODE REVIEW

**Review by max-friedman — COMMENTED** [review]
Are all these files being imported or did you write any of them? Just wondering which you need me to review

**Comment by tino-ai** [comment]
> Are all these files being imported or did you write any of them? Just wondering which you need me to review

**Comment by tin0d0** [comment]
> Are all these files being imported or did you write any of them? Just wondering which you need me to review

they are all imported from code mirror, nothing written by me.

**Review by g-luo — COMMENTED** [review]
not sure if we want to merge all these languages now, as it's not super related to any of the features we're building. Maybe we can discuss this support later then merge?

**Pull request closed without merging**
